import {useState,useEffect,useRef} from 'react';
import CareerAtlas from './components/CareerAtlas';
import {career,community} from './data/career';
import {articles} from './data/articles';
import resume from './data/profile.pdf?inline';

function Mark({item}){return <span className={`company-mark mark-${item.id}`} style={{'--company':item.color}} aria-hidden="true">{item.mark}</span>;}
function Article({article,onClose}){
 const dialog=useRef(null),progress=useRef(null);
 useEffect(()=>{const el=dialog.current;el.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};},[]);
 return <dialog ref={dialog} className={`reader theme-${article.theme}`} onCancel={e=>{e.preventDefault();onClose();}} aria-labelledby="article-title" style={{'--article':article.color}} onScroll={e=>{const t=e.currentTarget;if(progress.current)progress.current.style.width=(t.scrollTop/Math.max(1,t.scrollHeight-t.clientHeight)*100)+"%";}}>
  <div ref={progress} className="reader-progress" style={{width:0}}/><div className="reader-nav"><span>AF / FIELD NOTES</span><button onClick={onClose} autoFocus>Close article <span>×</span></button></div>
  <article><header className="article-head"><div className="eyebrow">{article.category} <span> / {article.number}</span></div><h1 id="article-title">{article.title}</h1><p className="article-deck">{article.intro}</p><div className="byline"><span className="avatar">AF</span><div><strong>Aditya Firoda</strong><br/><span>{article.tech} · {Math.max(2,Math.ceil(article.body.replace(/<[^>]*>/g,'').split(/\s+/).length/200))} min read</span></div></div></header>
  <div className={`article-animation animation-${article.theme}`} aria-hidden="true"><span>{article.theme==='map'?'28.61° N / 77.20° E':article.theme==='scan'?'LOCATE → SEGMENT → RECOGNIZE':article.theme==='search'?'INDEX → HASH → MATCH':article.theme==='vision'?'INPUT → DEHAZE → DETECT':'BUILD → EXPLORE → LEARN'}</span><i/><i/><i/></div>
  {article.note&&<aside className="editor-note"><strong>Context for this archive</strong><p>{article.note}</p></aside>}<div className="article-body" dangerouslySetInnerHTML={{__html:article.body}}/>
  <footer className="article-footer"><span>From the builder archive / {article.original}</span><button onClick={onClose}>Back to the portfolio ↗</button></footer></article>
 </dialog>;
}
export default function App(){
 const [hover,setHover]=useState(null),[selected,setSelected]=useState(null),[scrollChapter,setScrollChapter]=useState(null),[paused,setPaused]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),[article,setArticle]=useState(null);
 const trigger=useRef(null);const active=hover??selected??scrollChapter;
 useEffect(()=>{const elements=[...document.querySelectorAll('[data-chapter]')];const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)setScrollChapter(Number(e.target.dataset.chapter));},{rootMargin:'-25% 0px -45% 0px',threshold:0});elements.forEach(e=>observer.observe(e));const topObserver=new IntersectionObserver(([e])=>{if(e.isIntersecting)setScrollChapter(null);},{threshold:.6});topObserver.observe(document.getElementById('top'));return()=>{observer.disconnect();topObserver.disconnect();};},[]);
 useEffect(()=>{const openHash=()=>{const id=location.hash.replace('#article/','');const match=articles.find(a=>a.id===id);setArticle(match||null);};openHash();addEventListener('hashchange',openHash);return()=>removeEventListener('hashchange',openHash);},[]);
 const openArticle=(a,e)=>{trigger.current=e.currentTarget;location.hash='article/'+a.id;};
 const closeArticle=()=>{history.replaceState(null,'',location.pathname+location.search+'#projects');setArticle(null);requestAnimationFrame(()=>trigger.current?.focus());};
 return <><a className="skip-link" href="#journey">Skip to career history</a><header className="site-header"><a href="#top" className="brand"><span>af.</span> Aditya Firoda</a><nav aria-label="Main navigation"><a href="#journey">The journey</a><a href="#projects">Selected work</a><a href="#about">About</a></nav><a className="resume-link" href={resume} download="Aditya-Firoda-Profile.pdf">Profile PDF <span>↓</span></a></header>
 <main><section className="hero" id="top"><div className="hero-copy"><div className="eyebrow"><span className="tiny-line"/> ENGINEER BY FOUNDATION. BUILDER BY INSTINCT.</div><h1>From systems<br/>to <em>possibilities.</em></h1><p>I’m Aditya. I’ve built for the internet’s edge, digital assessments and healthcare. Now, at ISB, I’m connecting that experience to product and strategy.</p><div className="hero-actions"><a className="primary-link" href="#journey">Explore my journey <span>↘</span></a><a href="#projects">Read my work <span>↗</span></a></div><div className="hero-footnote"><span>ISB CLASS OF 2027</span><span>SOFTWARE → PRODUCT & STRATEGY</span></div></div>
 <div className="hero-atlas"><CareerAtlas active={active} onSelect={i=>{setSelected(i);document.getElementById('career-selector').scrollIntoView({behavior:paused?'instant':'smooth',block:'center'});}} paused={paused} onPause={()=>setPaused(v=>!v)}/><p className="atlas-caption"><span>Five chapters. One evolving perspective.</span><a href="#journey" aria-label="Explore the career chapters">↓</a></p></div></section>
 <section className="career-selector" id="career-selector" aria-label="Explore companies" onPointerLeave={()=>setHover(null)} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setHover(null);}}><div className="selector-label">THE JOURNEY<br/><span>Hover to explore · Click to hold</span></div><div className="company-buttons">{career.map((c,i)=><button key={c.id} style={{'--company':c.color}} className={active===i?'company-button active':'company-button'} aria-expanded={active===i} aria-controls="career-peek" onPointerEnter={e=>{if(e.pointerType==='mouse')setHover(i);}} onFocus={()=>setHover(i)} onClick={()=>{setSelected(v=>v===i?null:i);setHover(null);}}><Mark item={c}/><span>{c.id==='isb'?'ISB':c.name}<small>{c.years}</small></span></button>)}</div>
 <div id="career-peek" className={'career-peek '+(active!==null?'is-open':'')} style={{'--company':career[active]?.color}}>{active!==null&&<div key={active} className="peek-content"><div><p className="eyebrow">CHAPTER {career[active].chapter}</p><h3>{career[active].name}</h3><p>{career[active].role}</p><a href={'#'+career[active].id} onClick={()=>{setHover(null);setSelected(null);}}>Read this chapter ↓</a>{selected!==null&&<button className="release" onClick={()=>{setSelected(null);setHover(null);}}>Release selection ×</button>}</div><div>{career[active].groups.map(g=><div key={g.title}><h4>{g.title}</h4><ul>{g.points.map(p=><li key={p}>{p}</li>)}</ul></div>)}</div></div>}</div></section>
 <section className="journey section-wrap" id="journey"><div className="section-heading"><div><p className="eyebrow">01 / EXPERIENCE</p><h2>A career built<br/>one problem at a time.</h2></div><p>From my first offline map to infrastructure serving millions of requests. The work, the context, and what changed.</p></div>
 <div className="journey-layout"><aside className="journey-rail"><span className="eyebrow">CHAPTERS</span>{career.map((c,i)=><a href={'#'+c.id} className={scrollChapter===i?'rail-active':''} key={c.id} style={{'--company':c.color}}><span>{c.chapter}</span>{c.id==='isb'?'ISB':c.name}<small>{c.years}</small></a>)}<p>Built with code.<br/>Shaped by people.</p></aside><div className="chapters">{career.map((c,i)=><article className={'chapter chapter-'+c.id} key={c.id} id={c.id} data-chapter={i} style={{'--company':c.color}}><div className="chapter-top"><Mark item={c}/><div><h3>{c.name}</h3><p>{c.period}</p></div><span className="chapter-number">{c.chapter}</span></div><h4>{c.title}</h4><p className="chapter-summary">{c.summary}</p><div className="chapter-role"><strong>{c.role}</strong><span>{c.location}</span></div><div className="impact"><strong>{c.metric}</strong><span>{c.metricLabel}</span><div className={'impact-animation '+c.id} aria-hidden="true">{[0,1,2,3,4,5,6].map(j=><i key={j} style={{'--i':j}}/>)}</div></div>{c.groups.map(g=><div className="achievement-group" key={g.title}><h5>{g.title}</h5><ul>{g.points.map(p=><li key={p}>{p}</li>)}</ul></div>)}<div className="tags">{c.skills.map(s=><span key={s}>{s}</span>)}</div></article>)}</div></div></section>
 <section className="projects section-wrap" id="projects"><div className="section-heading"><div><p className="eyebrow">02 / THE BUILDER ARCHIVE</p><h2>Behind every build,<br/>a story worth sharing.</h2></div><p>Field notes from experiments in mapping, computer vision, search and the web. Original writing, in a new reading experience.</p></div><div className="project-list">{articles.map(a=><button className={'project-row theme-'+a.theme} key={a.id} style={{'--article':a.color}} onClick={e=>openArticle(a,e)}><div className="project-art"><img src={a.image} alt="" loading="lazy"/><div className="project-art-overlay"/><span>{a.tech}</span></div><div className="project-text"><span className="eyebrow">{a.number} / {a.category}</span><h3>{a.title}</h3><p>{a.intro}</p><span className="read-story">{a.id==='interactive-web-platform'?'View archive':'Read the story'} ↗</span></div></button>)}</div></section>
 <section className="about section-wrap" id="about"><div><p className="eyebrow">03 / BEYOND THE BUILD</p><h2>Systems matter.<br/><em>People, more.</em></h2><p className="about-copy">My foundation is computer science. My experience spans production systems, customer problems and cross-functional delivery. At ISB, I’m widening the lens to the business decisions behind the build.</p><p className="education">VIT · B.Tech, Computer Science · 2016–2020<br/>ISB · Postgraduate programme · 2026–2027</p></div><div className="community"><h3>Giving back</h3>{community.map(([date,name,copy])=><article key={name}><span>{date}</span><h4>{name}</h4><p>{copy}</p></article>)}</div></section>
 <footer className="contact section-wrap" id="contact"><p className="eyebrow">LET’S CONNECT</p><h2>What could we<br/><em>build together?</em></h2><a className="contact-email" href="mailto:adityafiroda@gmail.com">adityafiroda@gmail.com ↗</a><div className="footer-bottom"><span>Aditya Firoda / Portfolio 2026</span><div><a href="https://www.linkedin.com/in/aditya-firoda/" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://github.com/Firoda" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://leetcode.com/firoda/" target="_blank" rel="noreferrer">LeetCode ↗</a><a href="#top">Back to top ↑</a></div></div></footer></main>{article&&<Article key={article.id} article={article} onClose={closeArticle}/>}<style>{paused?'*,*::before,*::after{animation-play-state:paused!important;scroll-behavior:auto!important}':''}</style></>;
}
